name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build docker image
      run: docker build . --file Dockerfile --tag engelb/myvaillant2mqtt:$(date +%s)

    - name: Push docker image
      run: |
        docker login -u engelb -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push engelb/myvaillant2mqtt:$(date +%s)
