name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: engelb
        password: ${{ secrets.DOCKER_HUB_SECRET }}

    - name: Set Version Tag with Timestamp
      run: echo "VERSION_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      run: |
        docker build -t engelb/myvaillant2mqtt:${{ env.VERSION_TAG }} .
        docker push engelb/myvaillant2mqtt:${{ env.VERSION_TAG }}

    - name: Also Push "latest" Tag
      run: |
        docker tag engelb/myvaillant2mqtt:${{ env.VERSION_TAG }} engelb/myvaillant2mqtt:latest
        docker push engelb/myvaillant2mqtt:latest
